### ISSUE TITLE
Duplicate locations

### ISSUE THREAD

**Issue by rafaeldjsm** [chrismeller/StarbucksLocations#1]
I detected some repeated location values, I believe it is because of the accuracy of the logitudes/latitudes in degrees.

Below is an example

https://gist.github.com/rafaeldjsm/447146112b0ab0ad4c5b18c6629da531

**Comment by chrismeller** [comment]
@rafaeldjsm yes, that seems correct. Please keep in mind that this data is very outdated by now. I'm going to archive this repo.
